version: '3'

services:
  web:
    build: .
    container_name: api-logs
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
  db:
    image: postgres:13
    volumes:    
      - ./postgres-data:/var/lib/postgresql/data 
    env_file:
      - ./.env
    ports:
      - 6432:5432 # conectar a porta host 6432  para container 5432


    